-- 025_replace_status_with_phase.sql
--
-- Replace the 4-value status taxonomy (Under Construction / Planned /
-- Delivered / Unknown) with 9 standardized lifecycle phases:
--   Concept / Planning / Design / Approval / EPC Award / Procurement /
--   Construction / Commissioning / Delivery
--
-- Steps:
--   1. Back up the old data (rollback path: projects_status_backup).
--   2. Rename projects.status → projects.phase (text, nullable).
--   3. Map existing values:
--        Delivered          → 'Delivery'
--        Under Construction → 'Construction' (default)
--                             'Procurement' when description mentions procurement
--        Planned            → 'Planning' (default)
--                             'Approval' when description mentions EIA / 环评
--                             'Design'   when description mentions FEED
--        Unknown            → NULL (待 AI 判断)
--   4. Add candidate_events.phase (text, nullable) — populated by the
--      --backfill-phases AI backfill / ai_event_extractor.
--
-- Run in Supabase SQL Editor. Frontend reads `phase` with a legacy
-- `status` fallback (src/lib/project_phase.ts), so old caches keep working.

